version: '2'
services:
  adminer:
    restart: always
    image: 'adminer'
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: password
    links:
      - db:db

  db:
    restart: always
    image: 'postgres:15'
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./dev/data/db:/var/lib/postgresql
      - ./dev/initdb:/docker-entrypoint-initdb.d:ro

  migrator:
    build:
      context: ../backend
      dockerfile: dev.dockerfile
    volumes:
      - ../backend/src:/app/src:ro
      - /app/node_modules
    command: |
      /bin/sh -c "
      echo 'Started; waiting for DB'
      while ! nc -z db 5432
        do sleep 1
      done
      npx nodemon --legacy-watch --watch src/migrations -e ts --exec \"npm run migrate\" --polling-interval 5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/migrate
      MIGRATE_DATABASE_URL: postgresql://postgres:password@db:5432/migrate

  tests:
    build:
      context: ../backend
      dockerfile: dev.dockerfile
    volumes:
      - ../backend/src:/app/src
      - /app/node_modules
    command: |
      /bin/sh -c "
      echo 'Started; waiting for DB'
      while ! nc -z db 5432 
        do sleep 1
      done
      npm run test -- --watchAll"
    depends_on:
      - db
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/test
      MIGRATE_DATABASE_URL: postgresql://postgres:password@db:5432/test
      HASH_SECRET: secret_salt
      JWT_KEY: secret

  backend:
    build:
      context: ../backend
      dockerfile: dev.dockerfile
    volumes:
      - ../backend/src:/app/src
      - /app/node_modules
    command: |
      /bin/sh -c "
      echo 'Started; waiting for DB'
      while ! nc -z db 5432 
        do sleep 1
      done
      npm run dev"
    depends_on:
      - db
      - migrator
    env_file:
      - ../.env
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/app
      MIGRATE_DATABASE_URL: postgresql://postgres:password@db:5432/migrate
      HASH_SECRET: secret_salt
      JWT_KEY: secret

  angular:
    build:
      context: ../frontend/angular
      dockerfile: dev.dockerfile
    volumes:
      - ../frontend/angular/src:/app/src
      - /app/node_modules
    env_file:
      - ../.env

  proxy:
    image: nginx:alpine
    volumes:
      - ./dev/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dev/data/nginx/logs:/var/log/nginx/
      - ../frontend/static:/usr/share/nginx/static:ro
    restart: always
    ports:
      - 80:80
    links:
      - angular:angular
      - adminer:adminer
      - docs:docs
      - backend:backend
      - internal-docs:internal-docs

  docs:
    image: squidfunk/mkdocs-material
    volumes:
      - ../frontend/docs:/docs

  internal-docs:
    image: squidfunk/mkdocs-material
    volumes:
      - ../frontend/internal-docs:/docs
