site_name: "PointControl Internal"
theme:
  name: 'material'
  logo: 'assets/logo.png'
  favicon: 'assets/logo.png'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - offline

markdown_extensions:
  - abbr
  - admonition
  - toc:
      permalink: true
