name: "App: Checks"
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  BackendTests:
    name: "Backend Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Run Tests
        working-directory: backend
        run: |
          npm ci
          npm test -- --ci